version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27019:27019'
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27019/mydb
